# Generated by Django 3.2.7 on 2022-01-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_trade_records',
            old_name='records_id',
            new_name='record_id',
        ),
    ]
