# Generated by Django 3.2.7 on 2022-01-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_trade_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(max_length=10)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('time', models.DateField()),
                ('isBuyer', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_app.website_users')),
            ],
        ),
    ]
